before:
  hooks:
    - go mod tidy
    - go mod download

builds:
  - <<: &build_defaults
      main: ./cmd/axis/main.go
      binary: axis
      ldflags:

      env:
        - CGO_ENABLED=0
    id: darwin
    goos:
      - darwin

  - <<: *build_defaults
    id: linux
    goos:
      - linux

  - <<: *build_defaults
    id: windows
    goos:
      - windows

archives:
  - replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64

checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: "{{ .Tag }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
