name: CI/CD

on: [push, pull_request]

jobs:
  build:
    name: Build [${{ matrix.os }}, go v${{ matrix.go }}]
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
        go: ['1.15']
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go }}
      - name: Build
        run: go build -v ./...
      - name: Test
        run: go test -race ./...
