name: CI

on: [push, pull_request]

jobs:
  build:
    name: For ${{ matrix.os }} using Go v${{ matrix.go }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        go: ["1.13", "1.14", "1.15"]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go }}
      - run: go mod download
      - run: >
          go build
            -v
            -ldflags="-X 'github.com/FantasticFiasco/axis-cli/internal/build.Version=TODO' -X 'github.com/FantasticFiasco/axis-cli/internal/build.Date=$(date +%F)'"
            ./cmd/axis
      - run: go test -race ./...
