name: Release

on:
  push:
    tags:
      - v*

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-go@v2
        with:
          go-version: '1.15'
      - name: Generate release notes
        run: go run ./scripts/releasenotes --version="${GITHUB_REF/refs\/tags\/v/}" > ./RELEASE_NOTES.md
      - uses: goreleaser/goreleaser-action@v2
        with:
          version: latest
          args: release --release-notes=./RELEASE_NOTES.md
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
